import Head from "next/head";
import Image from "next/image";
import Login from "./login";
import { useState } from "react";
import ChatComponents from "../components/ChatComponents";
import { useRouter } from "next/router";

export default function Home() {
  const [user, setUser] = useState(false);
  const router = useRouter();

  if (user) return <Login />;

  return (
    <div className=" w-full h-screen">
      <Head>
        <title>Timely App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://static.vecteezy.com/system/resources/previews/013/821/913/original/minimal-blue-cartoon-alarm-clock-3d-rendering-icon-on-transparent-background-png.png"
        />
      </Head>
      <main className=" w-full  bg-[#e36c4d] h-screen grid grid-cols-10">
        <div className=" col-span-2 bg-gray-800 flex items-center space-y-3 pt-10 flex-col ">
          <div className="text-white  cursor-pointer   font-bold  flex justify-center items-center rounded-md border px-4 ">
            <button className="text-white  font-bold  flex justify-center items-center rounded-md px-4 py-1">
              Add New Chat
            </button>
            <img className="w-10" src="/add.gif" alt="..." />
          </div>

          <ChatComponents />
        </div>
        <div className=" relative col-span-8">
          <div className=" bg-orange-800 p-2 rounded-full right-10 absolute bottom-10">
            <img className="w-10" src="/gmail.gif" alt="" />
          </div>
        </div>
      </main>
    </div>
  );
}
